function assertHighSlewArbitraryWaveformWithinSystem( ...
        waveform, firstValue, lastValue, system, segmentName)
    % Match mr.makeArbitraryGrad's center-sampled boundary/slew convention.
    waveform = waveform(:);
    slew = [2*(firstValue-waveform(1)); ...
        waveform(2:end)-waveform(1:end-1); ...
        2*(waveform(end)-lastValue)] / system.gradRasterTime;
    gradPeak = max(abs(waveform));
    slewPeak = max(abs(slew));
    tol = 1 + 1e-10;
    assert(gradPeak <= system.maxGrad*tol, ...
        '%s gradient %.9g exceeds assigned limit %.9g Hz/m.', ...
        segmentName, gradPeak, system.maxGrad);
    assert(slewPeak <= system.maxSlew*tol, ...
        '%s slew %.9g exceeds assigned limit %.9g Hz/m/s.', ...
        segmentName, slewPeak, system.maxSlew);
end
